name: loan-approval-model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.4.1
    - pandas==2.2.0
    - numpy==1.26.3
    - matplotlib==3.8.2
    - seaborn==0.13.1    - joblib==1.3.2
    - dagshub==0.4.2
